"""new db

Revision ID: 770aaf4937d3
Revises: 
Create Date: 2026-04-03 12:51:12.641846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '770aaf4937d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enemy_type',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('life_points', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('reward_or', sa.Integer(), nullable=False),
    sa.Column('is_boss', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tower_type',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('base_damage', sa.Integer(), nullable=False),
    sa.Column('basic_scope', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('basic_attack_speed', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('max_level', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('pseudo', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pseudo')
    )
    op.create_table('game_score',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_user', sa.Uuid(), nullable=False),
    sa.Column('score', sa.BigInteger(), nullable=False),
    sa.Column('wave_reached', sa.Integer(), nullable=False),
    sa.Column('play_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_score_id_user'), 'game_score', ['id_user'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_user', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_revoke', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_refresh_token_id_user'), 'refresh_token', ['id_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_id_user'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_game_score_id_user'), table_name='game_score')
    op.drop_table('game_score')
    op.drop_table('users')
    op.drop_table('tower_type')
    op.drop_table('enemy_type')
    # ### end Alembic commands ###
